#
# This source file is part of the Stanford LLMonFHIR project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Static Analysis

on:
  workflow_dispatch:


concurrency:
  group: Static-Analysis-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codeql:
    name: CodeQL
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    permissions:
      security-events: write
      actions: read
      contents: read
    with:
      codeql: true
      fastlanelane: codeql
